import {StyleSheet, Dimensions} from 'react-native';
import {RFPercentage, RFValue} from 'react-native-responsive-fontsize';
import Fonts from './Fonts';
import Colors from './Colors';

export default {
  auth_safeArea: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  splashImage: {
    height: Dimensions.get('window').height * 0.5475,
    width: Dimensions.get('window').width,
    resizeMode: 'cover',
  },
  splashHeader: {
    fontFamily: Fonts.italic,
    fontSize: RFValue(32),
    marginHorizontal: RFValue(40),
    textAlign: 'center',
    alignSelf: 'center',
    fontWeight: '400',
    color: Colors.white,
  },
  splashDescription: {
    fontFamily: Fonts.regular,
    fontSize: RFValue(15),
    textAlign: 'center',
    alignSelf: 'center',
    width: RFValue(217),
    fontWeight: '400',
    color: Colors.white,
    marginTop: RFValue(24),
  },
  splashTextualView: {alignItems: 'center', marginTop: RFValue(40)},
  button: {
    borderRadius: RFValue(10),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: Colors.white,
    width: '80%',
    height: RFValue(50),
    marginTop: RFValue(43),
  },
  buttonText: {
    fontSize: RFValue(18),
    fontFamily: Fonts.regular,
    color: Colors.primary,
  },
  startHeader: {
    fontFamily: Fonts.regular,
    fontSize: RFValue(24),
    fontWeight: '500',
    textAlign: 'center',
    alignSelf: 'center',
    color: Colors.white,
    marginTop: RFValue(96),
  },
  startDescription: {
    fontFamily: Fonts.regular,
    fontSize: RFValue(15),
    textAlign: 'center',
    alignSelf: 'center',
    width: RFValue(217),
    fontWeight: '400',
    color: Colors.white,
    marginTop: RFValue(10),
  },
  startImage: {
    width: Dimensions.get('window').width,
    height: RFValue(90),
    resizeMode: 'contain',
    marginVertical: RFValue(80),
  },
  startAlreadyMember: {
    fontSize: RFValue(16),
    color: Colors.white,
    fontWeight: '400',
    fontFamily: Fonts.regular,
    alignSelf: 'center',
    marginTop: RFValue(35),
  },
  startLogin: {
    fontSize: RFValue(20),
    color: Colors.white,
    fontWeight: '400',
    fontFamily: Fonts.regular,
    alignSelf: 'center',
    marginTop: RFValue(5),
  },
  loginImage: {
    width: RFValue(150),
    height: RFValue(50),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: RFValue(30),
  },
  textFieldView: {
    marginTop: RFValue(10),
    marginHorizontal: RFValue(25),
    borderRadius: RFValue(7),
    borderWidth: RFValue(1),
    borderColor: Colors.white,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: RFValue(15),
  },
  richBox: {
    height: RFValue(100),
  },
  textField: {
    flex: 1,
    fontFamily: Fonts.regular,
    fontSize: RFValue(15),
    color: Colors.white,
  },
  loginSocialView: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: RFValue(10),
  },
  socialButton: {
    height: RFValue(45),
    width: RFValue(45),
    backgroundColor: Colors.white,
    borderRadius: RFValue(4),
    marginHorizontal: RFValue(5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleIcon: {
    height: RFValue(25),
    width: RFValue(25),
  },
  absoluteBottom: {
    position: 'absolute',
    bottom: RFValue(45),
    alignSelf: 'center',
  },
  forgotPassword: {
    marginRight: RFValue(25),
    alignSelf: 'flex-end',
  },
  forgotPasswordText: {
    color: Colors.white,
    fontWeight: '400',
    fontFamily: Fonts.regular,
    alignSelf: 'center',
    marginTop: RFValue(10),
    fontSize: RFValue(10),
  },
  forgotDescription: {
    fontFamily: Fonts.regular,
    fontSize: RFValue(15),
    textAlign: 'center',
    alignSelf: 'center',
    marginHorizontal: RFValue(20),
    fontWeight: '400',
    color: Colors.white,
    marginVertical: RFValue(20),
  },
  scrollView: {
    paddingBottom: RFValue(30),
  },
  loader: {
    alignSelf: 'center',
  },
  subscriptionCard: {
    marginTop: RFValue(10),
    marginHorizontal: RFValue(20),
    height: RFValue(50),
    backgroundColor: Colors.white,
    alignItems: 'center',
    borderRadius: RFValue(7),
    flexDirection: 'row',
    padding: RFValue(10),
  },
  subscriptionSelector: {
    borderColor: Colors.primary,
    borderWidth: RFValue(1),
    borderRadius: RFValue(20) / 2,
    height: RFValue(20),
    width: RFValue(20),
    alignSelf: 'center',
    justifyContent: 'center',
  },
  subscriptionTextArea: {marginHorizontal: RFValue(10), flex: 1},
  subscriptionText: {
    color: Colors.black,
    fontWeight: '400',
    fontFamily: Fonts.regular,
    fontSize: RFValue(12),
  },
  subscriptionImageGroup: {height: RFValue(35), resizeMode: 'contain'},
  divider10: {marginVertical: RFValue(5)},
  divider20: {marginVertical: RFValue(10)},
  divider30: {marginVertical: RFValue(15)},
  padder10: {marginHorizontal: RFValue(5)},
  padder20: {marginHorizontal: RFValue(10)},
  padder30: {marginHorizontal: RFValue(15)},
  description: {
    color: Colors.white,
    fontSize: RFValue(16),
    alignSelf: 'center',
    fontFamily: Fonts.regular,
  },
  paymentCardArea: {
    alignItems: 'center',
    marginHorizontal: RFValue(25),
    flexDirection: 'row',
    marginTop: RFValue(20),
  },
  paymentCard: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 0.5,
    marginLeft: RFValue(7),
    marginRight: RFValue(7),
    borderWidth: RFValue(1),
    borderColor: Colors.white,
    borderRadius: RFValue(10),
    height: RFValue(80),
  },
  paymentCardImage: {
    height: RFValue(25),
    resizeMode: 'contain',
  },
  headerTitle: {
    color: Colors.black,
    fontSize: RFValue(20),
    marginHorizontal: RFValue(10),
    fontWeight: '400',
    fontFamily: Fonts.regular,
  },
  headerBar: {
    flexDirection: 'row',
    padding: RFValue(20),
    alignItems: 'center',
  },
  headerBackButton: {
    height: RFValue(40),
    width: RFValue(40),
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileImage: {
    height: RFValue(135),
    width: RFValue(145),
    resizeMode: 'contain',
  },
  profileName: {
    fontSize: RFValue(16),
    color: Colors.black,
    alignSelf: 'center',
    textAlign: 'center',
    fontFamily: Fonts.regular,
  },
  picSelectorImageView: {
    height: RFValue(250),
    width: Dimensions.get('window').width * 0.9,
    borderRadius: RFValue(15),
    overflow: 'hidden',
  },
  picSelectorImage: {
    height: RFValue(250),
    width: Dimensions.get('window').width * 0.9,
    resizeMode: 'contain',
  },
  picSelectorRemove: {
    position: 'absolute',
    top: RFValue(10),
    right: RFValue(10),
  },
  picSelectorAddPic: {
    height: RFValue(80),
    width: RFValue(80),
    borderRadius: RFValue(7),
    marginRight: RFValue(10),
    marginTop: RFValue(10),
    justifyContent: 'center',
  },
  picSelectorListPic: {
    height: RFValue(80),
    width: RFValue(80),
    resizeMode: 'center',
  },
  profilePressable: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: RFValue(10),
    marginHorizontal: RFValue(20),
    padding: RFValue(15),
  },
  editImage: {
    backgroundColor: Colors.white,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    height: RFValue(38),
    width: RFValue(38),
    bottom: -15,
    right: -15,
  },
  subText: {
    fontSize: RFValue(13),
    color: 'rgba(0, 0, 0, 0.5)',
    fontWeight: '300',
    fontFamily: Fonts.regular,
  },
  viewOverlay: {
    flex: 1,
    borderTopLeftRadius: RFValue(20),
    borderTopRightRadius: RFValue(20),
    backgroundColor: Colors.white,
    padding: RFValue(25),
    marginTop: -1 * RFValue(30),
  },
  Bg: {
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').width / 4,
    width: Dimensions.get('window').width / 4,
  },
  innerBg: {
    // margin: RFValue(15),
  },
  sliderImage: {
    marginVertical: RFValue(10),
    alignSelf: 'center',
    height: RFValue(150),
    width: Dimensions.get('window').width * 0.86,
  },
  sliderText: {
    fontFamily: Fonts.italic,
    color: Colors.black,
    width: Dimensions.get('window').width * 0.45,
    height: RFValue(170),
    fontSize: RFValue(20),
    paddingTop: RFValue(20),
    paddingLeft: RFValue(20),
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  viewAllNearBy: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: RFValue(25),
  },
  nearByText: {
    fontSize: RFValue(16),
    fontFamily: Fonts.regular,
    fontWeight: '600',
    color: Colors.black,
    flex: 1,
  },
  viewAll: {
    fontFamily: Fonts.italic,
    fontSize: RFValue(13),
    color: '#F5C02D',
    marginRight: RFValue(10),
  },
  viewAllIcon: {
    backgroundColor: '#F5C02D',
    borderRadius: RFValue(7),
    height: RFValue(25),
    width: RFValue(25),
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselPetName: {
    fontSize: RFValue(11),
    color: Colors.black,
    fontFamily: Fonts.italic,
  },
  carouselPetLocation: {
    fontSize: RFValue(8),
    fontFamily: Fonts.regular,
  },
  carouselPetAbsoluteLayout: {
    left: 0,
    bottom: RFValue(20),
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255,0.6)',
    borderTopRightRadius: RFValue(20),
    borderBottomRightRadius: RFValue(20),
    paddingHorizontal: RFValue(7),
    paddingVertical: RFValue(2),
  },
  carouselFavourite: {
    position: 'absolute',
    top: RFValue(7),
    right: RFValue(7),
    height: RFValue(30),
    alignItems: 'center',
    justifyContent: 'center',
    width: RFValue(30),
    borderRadius: RFValue(30) / 2,
    backgroundColor: Colors.primary,
  },
};
